spring:
  application:
    name: encore
  banner:
    location: classpath:asciilogo.txt
  cloud:
    config:
      import-check:
        enabled: false
  threads:
    virtual:
      enabled: true
logging:
  config: classpath:logback-json.xml

springdoc:
  paths-to-exclude: /profile/encoreJobs,/profile
  swagger-ui:
    operations-sorter: alpha
    tags-sorter: alpha
    disable-swagger-default-url: true
  enable-kotlin: false # springdoc does not work with graalvm if enabled (v2.8.13)
server:
  forward-headers-strategy: framework
